// Code generated by "go generate gonum.org/v1/gonum/unit/constant”; DO NOT EDIT.

// Copyright ©2019 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package constant

import (
	"fmt"
	"testing"
)

func TestElementaryChargeFormat(t *testing.T) {
	for _, test := range []struct {
		format string
		want   string
	}{
		{"%v", "1.6021766208e-19 A s"},
		{"%.1v", "2e-19 A s"},
		{"%50.1v", "                                         2e-19 A s"},
		{"%50v", "                              1.6021766208e-19 A s"},
		{"%1v", "1.6021766208e-19 A s"},
		{"%#v", "constant.elementaryChargeUnits(1.6021766208e-19)"},
		{"%s", "%!s(constant.elementaryChargeUnits=1.6021766208e-19 A s)"},
	} {
		got := fmt.Sprintf(test.format, ElementaryCharge)
		if got != test.want {
			t.Errorf("Format %q: got: %q want: %q", test.format, got, test.want)
		}
	}
}
