// Code generated by "go generate gonum.org/v1/gonum/unit/constant”; DO NOT EDIT.

// Copyright ©2019 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package constant

import (
	"fmt"

	"gonum.org/v1/gonum/unit"
)

// LightSpeedInVacuum is the c constant, the speed of light in a vacuum.
// The dimensions of LightSpeedInVacuum are m s^-1.
const LightSpeedInVacuum = lightSpeedInVacuumUnits(2.99792458e+08)

type lightSpeedInVacuumUnits float64

// Unit converts the lightSpeedInVacuumUnits to a *unit.Unit
func (cnst lightSpeedInVacuumUnits) Unit() *unit.Unit {
	return unit.New(float64(cnst), unit.Dimensions{
		unit.LengthDim: 1,
		unit.TimeDim:   -1,
	})
}

func (cnst lightSpeedInVacuumUnits) Format(fs fmt.State, c rune) {
	switch c {
	case 'v':
		if fs.Flag('#') {
			fmt.Fprintf(fs, "%T(%v)", cnst, float64(cnst))
			return
		}
		fallthrough
	case 'e', 'E', 'f', 'F', 'g', 'G':
		p, pOk := fs.Precision()
		w, wOk := fs.Width()
		switch {
		case pOk && wOk:
			fmt.Fprintf(fs, "%*.*"+string(c), w, p, cnst.Unit())
		case pOk:
			fmt.Fprintf(fs, "%.*"+string(c), p, cnst.Unit())
		case wOk:
			fmt.Fprintf(fs, "%*"+string(c), w, cnst.Unit())
		default:
			fmt.Fprintf(fs, "%"+string(c), cnst.Unit())
		}
	default:
		fmt.Fprintf(fs, "%%!"+string(c)+"(constant.lightSpeedInVacuumUnits=%v m s^-1)", float64(cnst))
	}
}
